# Blog settings
permalink: /blog/:title


# My variables
name: yuan'blog
description: 世界是美好的，甚至黑暗和沉寂也是如此。无论出于什么样环境，都要不断努力，都要学会满足。--海伦·凯勒
url: https://oldyuan.com
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

gems: [ "jemoji" ]

