# Blog settings
permalink: /blog/:title


# My variables
name: yuan'blog
description: 世界是美好的，甚至黑暗和沉寂也是如此。无论出于什么样环境，都要不断努力，都要学会满足。--海伦·凯勒
url: https://oldyuan.com
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
## Conversion
# Markdown Options https://jekyllrb.com/docs/configuration/markdown/
# https://github.com/github/jekyll-commonmark-ghpages

markdown: CommonMarkGhPages # GFM
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]


# markdown: kramdown
# highlighter: rouge
# lsi: false
# excerpt_separator: "\n\n"
# incremental: false

# Markdown Processing https://jekyllrb.com/docs/configuration/markdown/
# kramdown: # https://kramdown.gettalong.org/options.html
  # input: GFM
  # header_offset: 0
  # hard_wrap: false
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # smart_quotes: lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false
